package edu.feutech.redu.sentiment

object MvlLexicon {
    val defaultEntries: Map<String, Double> = mapOf(
        // Expert-validated Filipino/Taglish MVL entries from Mr. Cadigal's review.
        "aliw" to 2.0,
        "ayaw" to -2.0,
        "ayos" to 2.0,
        "bilib" to 3.0,
        "bobo" to -4.0,
        "buhay" to 0.0,
        "bwisit" to -3.0,
        "dusa" to -3.0,
        "gago" to -4.0,
        "galing" to 3.0,
        "galit" to -3.0,
        "gusto" to 2.0,
        "hirap" to -2.0,
        "inis" to -2.0,
        "iyak" to -2.0,
        "kasalanan" to -2.0,
        "kilig" to 3.0,
        "kupal" to -4.0,
        "ligaya" to 3.0,
        "lodi" to 3.0,
        "luha" to -2.0,
        "lungkot" to -3.0,
        "mabait" to 3.0,
        "maganda" to 3.0,
        "mahal" to 3.0,
        "mahirap" to -2.0,
        "masama" to -3.0,
        "masaya" to 3.0,
        "nakagagalit" to -3.0,
        "nakakagalit" to -3.0,
        "nakaiinis" to -2.0,
        "nakakainis" to -2.0,
        "nakalulungkot" to -3.0,
        "nakakalungkot" to -3.0,
        "nakatatakot" to -2.0,
        "nakakatakot" to -2.0,
        "ngiti" to 2.0,
        "paborito" to 3.0,
        "pag-asa" to 3.0,
        "pangit" to -3.0,
        "payapa" to 2.0,
        "petmalu" to 3.0,
        "pighati" to -3.0,
        "poot" to -4.0,
        "sakit" to -3.0,
        "salamat" to 3.0,
        "selos" to -2.0,
        "sigla" to 3.0,
        "sisi" to -2.0,
        "swerte" to 3.0,
        "takot" to -2.0,
        "talo" to -2.0,
        "tanga" to -4.0,
        "tawa" to 2.0,
        "tiwala" to 3.0,
        "tuwa" to 3.0,
        "wagi" to 3.0
    )

    val tagalogStopWords: Map<String, Double> = mapOf(
        "ang" to 0.0,
        "ng" to 0.0,
        "sa" to 0.0,
        "mga" to 0.0,
        "na" to 0.0,
        "ay" to 0.0,
        "at" to 0.0,
        "pa" to 0.0,
        "si" to 0.0,
        "ni" to 0.0,
        "kay" to 0.0,
        "lang" to 0.0,
        "naman" to 0.0,
        "ba" to 0.0,
        "ito" to 0.0,
        "iyon" to 0.0,
        "doon" to 0.0,
        "dito" to 0.0,
        "nito" to 0.0,
        "niyan" to 0.0,
        "nila" to 0.0,
        "namin" to 0.0,
        "ninyo" to 0.0,
        "ako" to 0.0,
        "ikaw" to 0.0,
        "siya" to 0.0,
        "kami" to 0.0,
        "tayo" to 0.0,
        "kayo" to 0.0,
        "sila" to 0.0,
        "ko" to 0.0,
        "mo" to 0.0,
        "niya" to 0.0,
        "akin" to 0.0,
        "iyo" to 0.0,
        "kanila" to 0.0,
        "kanya" to 0.0,
        "ating" to 0.0,
        "aming" to 0.0,
        "inyong" to 0.0,
        "kapag" to 0.0,
        "dahil" to 0.0,
        "pero" to 0.0,
        "kasi" to 0.0,
        "upang" to 0.0,
        "habang" to 0.0,
        "bago" to 0.0,
        "kaya" to 0.0,
        "sana" to 0.0,
        "nga" to 0.0,
        "din" to 0.0,
        "rin" to 0.0,
        "raw" to 0.0,
        "daw" to 0.0,
        "kung" to 0.0,
        "para" to 0.0,
        "kapwa" to 0.0,
        "lamang" to 0.0
    )

    val englishStopWords: Map<String, Double> = mapOf(
        "the" to 0.0, "a" to 0.0, "an" to 0.0, "and" to 0.0, "or" to 0.0, "but" to 0.0,
        "if" to 0.0, "because" to 0.0, "as" to 0.0, "until" to 0.0, "while" to 0.0,
        "of" to 0.0, "at" to 0.0, "by" to 0.0, "for" to 0.0, "with" to 0.0, "about" to 0.0,
        "against" to 0.0, "between" to 0.0, "into" to 0.0, "through" to 0.0, "during" to 0.0,
        "before" to 0.0, "after" to 0.0, "above" to 0.0, "below" to 0.0, "to" to 0.0,
        "from" to 0.0, "up" to 0.0, "down" to 0.0, "in" to 0.0, "out" to 0.0, "on" to 0.0,
        "off" to 0.0, "over" to 0.0, "under" to 0.0, "again" to 0.0, "further" to 0.0,
        "then" to 0.0, "once" to 0.0, "here" to 0.0, "there" to 0.0, "when" to 0.0,
        "where" to 0.0, "why" to 0.0, "how" to 0.0, "all" to 0.0, "any" to 0.0,
        "both" to 0.0, "each" to 0.0, "few" to 0.0, "more" to 0.0, "most" to 0.0,
        "other" to 0.0, "some" to 0.0, "such" to 0.0, "no" to 0.0, "nor" to 0.0,
        "not" to 0.0, "only" to 0.0, "own" to 0.0, "same" to 0.0, "so" to 0.0,
        "than" to 0.0, "too" to 0.0, "very" to 0.0, "s" to 0.0, "t" to 0.0,
        "can" to 0.0, "will" to 0.0, "just" to 0.0, "don" to 0.0, "should" to 0.0,
        "now" to 0.0, "d" to 0.0, "ll" to 0.0, "m" to 0.0, "o" to 0.0,
        "re" to 0.0, "ve" to 0.0, "y" to 0.0, "i" to 0.0, "me" to 0.0,
        "my" to 0.0, "myself" to 0.0, "we" to 0.0, "our" to 0.0, "ours" to 0.0,
        "ourselves" to 0.0, "you" to 0.0, "your" to 0.0, "yours" to 0.0,
        "yourself" to 0.0, "yourselves" to 0.0, "he" to 0.0, "him" to 0.0,
        "his" to 0.0, "himself" to 0.0, "she" to 0.0, "her" to 0.0, "hers" to 0.0,
        "herself" to 0.0, "it" to 0.0, "its" to 0.0, "itself" to 0.0,
        "they" to 0.0, "them" to 0.0, "their" to 0.0, "theirs" to 0.0,
        "themselves" to 0.0, "what" to 0.0, "which" to 0.0, "who" to 0.0,
        "whom" to 0.0, "this" to 0.0, "that" to 0.0, "these" to 0.0,
        "those" to 0.0, "am" to 0.0, "is" to 0.0, "are" to 0.0, "was" to 0.0,
        "were" to 0.0, "be" to 0.0, "been" to 0.0, "being" to 0.0, "have" to 0.0,
        "has" to 0.0, "had" to 0.0, "having" to 0.0, "do" to 0.0, "does" to 0.0,
        "did" to 0.0, "doing" to 0.0, "would" to 0.0, "could" to 0.0,
        "ought" to 0.0
    )

    val extensionLexicon: Map<String, Double> = defaultEntries + tagalogStopWords + englishStopWords

    fun merge(vararg lexicons: Map<String, Double>): Map<String, Double> =
        lexicons.fold(extensionLexicon) { acc, next -> acc + next.mapKeys { it.key.lowercase() } }
}
