// ==========================================
// CHAPTER 5: CONCLUSION
// ==========================================

= CONCLUSION

This chapter presents the summary of findings and conclusions based on the completed data analysis in Chapter 4. The conclusions are written within the study's actual scope: a pilot-scale software-engineering evaluation of a privacy-preserving Android system for heuristic doomscrolling-related risk estimation.

== Summary of Findings

For the first research question, the study found that the implemented Android system could support privacy-preserving local risk estimation using observable behavioral and sentiment-related proxies. The final logs contained 10,134 sessions across TikTok, Facebook Reels, and Instagram Reels, with 8,817 sessions classified as sentiment-reliable and 1,317 sessions classified as sentiment-unreliable. The system implemented local processing, study-code-based export, text-first VADER-compatible sentiment analysis, Filipino/Taglish MVL support, a no-text VLM fallback, fuzzy inference, and conservative fallback handling. The MVL concordance data also showed exact agreement between the expert ratings and deployed runtime valences for all 57 runtime lexicon entries.

For the second research question, the intervention group showed larger Week 1-to-Week 2 reductions than the control group across the four primary outcomes. Session duration, video dwell time, NSD, and the self-reported Doomscrolling Scale all favored the intervention group after the final assumption-selected tests and Holm-Bonferroni correction. Supplementary results for sessions per day and DSI followed the same direction, and the within-intervention paired comparisons showed reductions from Week 1 to Week 2.

For the third research question, Week 1 DSI showed a strong positive baseline association with the Week 1 Doomscrolling Scale among the 48 eligible participants. The composite DSI had Spearman's $rho = 0.76$, supporting convergent plausibility, while Week 1 mean daily session duration had the highest rank association with self-report at $rho = 0.92$. The finding supports convergence between DSI and self-reported doomscrolling rather than superiority of the composite over its individual components.

For the fourth research question, the user evaluation met all pre-set software-acceptability targets. Functional Suitability, Performance Efficiency, Reliability, SUS Usability, TAM Perceived Usefulness, and TAM Perceived Ease of Use all reached the favorable thresholds. The SUS composite was 80.95, above the study target of 70. Cronbach's alpha values ranged from 0.717 to 0.957, meeting the $alpha >= 0.70$ internal-consistency benchmark. Open-ended feedback showed that users valued the dashboard, break reminders, privacy approach, and self-monitoring support, while also identifying needs around prompt timing, onboarding, score clarity, platform monitoring, breathing-break length, export transparency, and battery/performance feedback.

For the fifth research question, both subject matter experts rated the system favorably. The software engineering expert gave an overall mean of 5.00, having evaluated both the system architecture and the algorithm design (including VADER accuracy, fuzzy logic effectiveness, and system scalability), while the digital well-being/behavioral psychology expert gave an overall mean of 4.33. Their comments supported the non-clinical framing, privacy-conscious design, and general intervention structure, while recommending clearer fallback criteria, clearer stored-data wording, softer risk terminology, and more configurable intervention behavior.

== Conclusions Based on Research Objectives and Questions

Based on the first research objective, the study concludes that the proposed system architecture was feasible for a bounded Android-based pilot deployment. The completed system combined Android Accessibility Service monitoring, local session tracking, text-first VADER-compatible sentiment scoring with the Filipino/Taglish Minimum Viable Lexicon, an on-device no-text VLM fallback using Moondream 0.5B, fuzzy inference, and adaptive prompting — all processed locally without retaining raw text or screen frames in the research dataset. Over the two-week deployment, the system produced 10,134 logged sessions across TikTok, Facebook Reels, and Instagram Reels, of which 8,817 (87.0%) were sentiment-reliable and 1,317 (13.0%) were classified as sentiment-unreliable and handled through the 2-input behavioral fallback. The Filipino MVL concordance data showed exact agreement between expert ratings and deployed runtime valences for all 57 runtime lexicon entries. The reliability-event audit identified high-OOV text as the dominant driver of sentiment-unreliability (69.5% of reliability events), followed by VLM-unresolved items (18.1%) and extraction failures (11.4%). The analytic time-complexity analysis confirmed that every core runtime component was bounded to at most $O(n)$ per item and $O(1)$ per fuzzy inference, with the VLM fallback carrying the largest constant cost but reserved only for no-text items. Prompt logs recorded 370 intervention events during Week 2, with `TAKE_BREAK` as the most frequent response (51.6%). Taken together, these results support the technical feasibility, operational stability, and privacy-preserving design of the architecture for a pilot-scale deployment.

Based on the second research objective, the study concludes that the intervention condition was associated with favorable observed short-term differences in logged usage metrics and self-reported doomscrolling scores. All four primary between-group outcomes — session duration ($t = -4.17$, $p < .001$, $d = -1.18$), video dwell time ($U = 124.0$, $p < .001$, $d = -1.33$), NSD ($U = 68.0$, $p < .001$, $d = -1.82$), and the self-reported Doomscrolling Scale ($U = 105.0$, $p < .001$, $d = -1.50$) — favored the intervention group after Holm-Bonferroni correction, with large effect sizes whose 95% confidence intervals all fell entirely below zero. The supplementary between-group results for mean sessions per day ($d = -0.82$) and DSI composite risk ($d = -1.84$) followed the same direction. Within the intervention group, paired comparisons also showed reductions from Week 1 to Week 2 for all four primary outcomes, with effect sizes ranging from $d_z = -0.88$ for session duration to $d_z = -1.28$ for NSD. These results support the promise of adaptive prompts as a short-term behavioral support mechanism under the study conditions, but they should be interpreted within the boundaries of a pilot-sized, two-week, non-blinded deployment with purposive-convenience sampling. Establishing long-term efficacy, disentangling prompt effects from monitoring awareness and novelty, and confirming generalizability require a longer deployment and a larger sample.

Based on the third research objective, the study concludes that the DSI has baseline convergent plausibility because it correlated strongly with the Doomscrolling Scale among the 48 eligible participants. The composite DSI had Spearman's $rho = 0.76$ ($p < .001$) and Pearson's $r = 0.82$ with the Week 1 self-reported Doomscrolling Scale. Its individual components also showed strong positive associations: Week 1 mean NSD had $rho = 0.76$ and $r = 0.83$, and Week 1 mean dwell time had $rho = 0.75$ and $r = 0.82$. However, Week 1 mean daily session duration had the highest rank association at $rho = 0.92$ ($r = 0.82$), indicating that a single behavioral proxy matched self-report more closely than the composite did on the rank statistic. Because the Pearson values for all predictors clustered tightly at $r approx 0.82$–$0.83$, the rank ordering rather than the linear relationship drove the duration advantage. The DSI is therefore best characterized as a transparent composite indicator that converges with self-report and captures multiple theoretical dimensions of the Doomscrolling Feedback Loop Model, but it does not demonstrate composite superiority over its individual components in this sample and still requires further validation and calibration.

Based on the fourth research objective, the study concludes that users evaluated the system favorably in terms of selected ISO/IEC 25010 characteristics, usability, and technology acceptance. All six evaluated constructs met their pre-set favorable thresholds: Functional Suitability (mean = 3.93), Performance Efficiency (mean = 4.09), Reliability (mean = 4.05), SUS Usability (composite score = 80.95, above the 70 target), TAM Perceived Usefulness (mean = 4.12), and TAM Perceived Ease of Use (mean = 4.09). When normalized to a common 0–100% scale, the six constructs clustered within a narrow 78.6%–82.4% band, indicating a uniformly positive assessment rather than an uneven profile. Cronbach's alpha values ranged from 0.717 (Reliability) to 0.957 (SUS), meeting the $alpha >= 0.70$ internal-consistency benchmark for every multi-item scale. Open-ended feedback themes showed that users valued the dashboard, break reminders, privacy approach, and self-monitoring support. The most frequently cited improvement needs were prompt timing (16% of coded themes), onboarding and setup guidance (12%), and score clarity (12%), followed by platform monitoring visibility (10%), breathing-break configurability (8%), export transparency (8%), and battery/performance feedback (6%). These qualitative findings indicate that the system was usable enough for pilot evaluation, but several parts of the user experience — particularly setup complexity, prompt tuning, score interpretation, and transparency around platform monitoring and exported data — need refinement before broader deployment.

Based on the fifth research objective, the study concludes that the system received favorable expert plausibility appraisal from the available SME reviewers. The software engineering expert (`SME-SE-01`) rated all six rubric areas at 5.00, resulting in an overall mean of 5.00, and evaluated the system from both a software architecture and algorithm design perspective — assessing the accuracy and reliability of VADER sentiment analysis, the effectiveness of the fuzzy logic decision-making pipeline, and the system's scalability for real-world deployment. The expert considered the hybrid VADER, fallback, and fuzzy inference approach appropriate for a non-clinical prototype while recommending clearer operational definitions for aggregate-only handling and fallback triggers. The digital well-being/behavioral psychology expert (`SME-PSY-01`) gave an overall mean of 4.33, with individual ratings of 4 or 5 across the six rubric dimensions, and supported the non-clinical self-monitoring framing and the Doomscrolling Feedback Loop Model as an appropriate theoretical basis. This expert also recommended softer risk terminology, clearer presentation of risk labels, a shorter or configurable pause-and-reset duration, and clearer stored-data wording. Both experts met the study-defined favorable target of 4.00, supporting the appropriateness of the privacy framing, heuristic logic, algorithm design, and intervention structure for a non-clinical prototype. While the software engineering expert provided evaluation of the algorithm design, a dedicated fuzzy-systems, data-science, or machine-learning reviewer would further strengthen the expert-validation claim, and the identified refinements — clearer fallback criteria, softer risk labels, stronger privacy wording, and more configurable intervention behavior — should be addressed before the system undergoes broader expert review or deployment.

Overall, the thesis concludes that the Heuristic Risk-State Estimation System is a defensible pilot prototype for privacy-preserving doomscrolling-related risk estimation and digital mindfulness prompting on Android short-form-video platforms. Its strongest contribution is the integration of local behavioral logging, text-first sentiment analysis, no-text fallback handling, fuzzy risk estimation, and user-facing prompts in one bounded software artifact. Its strongest limitation is that the evidence remains exploratory: the sample was purposive-convenience, the study lasted two weeks, some sentiment-dependent outcomes excluded unreliable sessions, and expert review was limited to two reviewers.

#pagebreak()
